name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      retryCount:
        description: '重试次数'
        default: '0'
        type: string
        required: false
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}

  retry-on-failure:
    needs: run-flutter-tag-build
    if: ${{ failure() && fromJSON(github.event.inputs.retryCount || '0') < 3 }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 计算下次重试次数
        id: calc_retry
        run: |
          current_retry=${{ github.event.inputs.retryCount || '0' }}
          next_retry=$((current_retry + 1))
          echo "next_retry=$next_retry" >> $GITHUB_OUTPUT
        timeout-minutes: 1

      - name: 触发新工作流
        run: |
          # 获取参数
          next_retry=${{ steps.calc_retry.outputs.next_retry }}
          repo="${{ github.repository }}"
          workflow_id="${{ github.workflow_id }}"
          ref="${{ github.ref }}"
          token="${{ secrets.RESTART_WORKFLOW_TOKEN }}"
          
          # 构建JSON payload（单行格式，避免换行问题）
          payload='{"ref": "'"$ref"'", "inputs": {"retryCount": "'"$next_retry"'"}}'
          
          # 构建完整的API URL
          api_url="https://api.github.com/repos/$repo/actions/workflows/$workflow_id/dispatches"
          
          # 执行curl命令（单行格式，彻底避免换行导致的参数拆分）
          response=$(curl --max-time 30 -s -w "%{http_code}" -X POST -H "Authorization: token $token" -H "Accept: application/vnd.github.v3+json" -d "$payload" "$api_url")
          
          # 提取状态码和响应体
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          # 检查结果
          if [ "$status_code" -eq 204 ]; then
            echo "✅ 成功触发第 $next_retry 次重试"
          else
            echo "❌ 触发失败，状态码: $status_code，响应: $body"
            exit 1
          fi
        timeout-minutes: 1

  max-retries-reached:
    needs: run-flutter-tag-build
    if: ${{ failure() && fromJSON(github.event.inputs.retryCount || '0') >= 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: 通知达到最大重试次数
        run: |
          echo "❌ 已达到最大重试次数 (3次)，工作流终止"
