name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      retryCount:
        description: '重试次数'
        default: '0'
        type: string  # 保持字符串类型
        required: false
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}

  retry-on-failure:
    needs: run-flutter-tag-build
    # 条件判断：失败且重试次数 < 3（仅用比较，不做加法）
    if: ${{ failure() && fromJSON(github.event.inputs.retryCount) < 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: 计算下次重试次数
        id: calc_retry
        run: |
          # 在 shell 中处理加法运算
          current_retry=${{ github.event.inputs.retryCount }}
          next_retry=$((current_retry + 1))
          echo "next_retry=$next_retry" >> $GITHUB_OUTPUT

      - name: 显示重试次数
        run: |
          echo "当前重试次数: ${{ github.event.inputs.retryCount }}"
          echo "下次重试次数: ${{ steps.calc_retry.outputs.next_retry }}"

      - name: 触发新工作流
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.RESTART_WORKFLOW_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow_id }}/dispatches \
            -d '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "retryCount": "${{ steps.calc_retry.outputs.next_retry }}"
              }
            }'

  max-retries-reached:
    needs: run-flutter-tag-build
    if: ${{ failure() && fromJSON(github.event.inputs.retryCount) >= 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: 通知达到最大重试次数
        run: |
          echo "已达到最大重试次数 (3次)，工作流终止"
